# Site settings
title: EVMA Fireside Chat
email: contact@evmafiresidechat.com
baseurl: ''
url: https://www.evmafiresidechat.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#990000'

# Footer settings
footer: EVMA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/6435119218/

# Build settings
markdown: kramdown
permalink: pretty
