# Site settings
title: EVMA Fireside Chat
email: contact@evmafiresidechat.com
baseurl: ''
url: https://www.evmafiresidechat.com
description: "Learn from entrepreneurs at various stages of the business cycle what it takes to turn an idea into a business.

Fireside Chat is an event hosted by USC Marshall's Entrepreneurship and Venture Management Club. Panelists will use their unique experiences as lenses for teaching lessons in entrepreneurship—providing students with deep tangible insights into understanding what it takes to succeed at starting their own venture."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#990000'

# Footer settings
footer: EVMA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/6435119218/

# Build settings
markdown: kramdown
permalink: pretty
